import { Service } from '../../types';

export const mockServices: Service[] = [
  {
    id: 'gst-001',
    title: 'GST Registration',
    clientName: 'Acme Corporation',
    organization: 'Acme Corp',
    email: 'acme@company.com',
    phone: '+91 98765 43210',
    category: 'GST',
    status: 'In Progress',
    priority: 'Medium',
    description: 'GST registration for new business entity.',
    progress: 75,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [3],
    documents: 3,
    startDate: '2024-07-15',
  },
  {
    id: 'tax-001',
    title: 'Income Tax Filing',
    clientName: 'Tech Solutions Pvt Ltd',
    organization: 'Tech Solutions',
    email: 'info@techsolutions.com',
    phone: '+91 87654 32109',
    category: 'Tax',
    status: 'Completed',
    priority: 'High',
    description: 'Annual income tax filing and compliance.',
    progress: 100,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [8],
    documents: 5,
    startDate: '2024-06-20',
  },
  {
    id: 'startup-001',
    title: 'Company Registration',
    clientName: 'Green Energy Startup',
    organization: 'Green Energy',
    email: 'contact@greenenergy.com',
    phone: '+91 76543 21098',
    category: 'Startup',
    status: 'New',
    priority: 'Low',
    description: 'Private limited company registration.',
    progress: 10,
    assignedTeam: 'Unassigned',
    assignedEmployeeIds: [],
    documents: 1,
    startDate: '2024-07-18',
  },
  {
    id: 'legal-001',
    title: 'Contract Review',
    clientName: 'Innovate LLC',
    organization: 'Innovate LLC',
    email: 'legal@innovate.com',
    phone: '+91 91234 56789',
    category: 'Legal',
    status: 'In Progress',
    priority: 'High',
    description: 'Review of vendor contracts for the new software procurement.',
    progress: 50,
    assignedTeam: 'Legal Team',
    assignedEmployeeIds: [],
    documents: 2,
    startDate: '2024-07-10',
  },
  {
    id: 'audit-001',
    title: 'Security Audit',
    clientName: 'SecureNet Inc.',
    organization: 'SecureNet',
    email: 'security@securenet.com',
    phone: '+91 89876 54321',
    category: 'Audit',
    status: 'New',
    priority: 'Medium',
    description: 'Annual security audit and penetration testing.',
    progress: 0,
    assignedTeam: 'IT Team',
    assignedEmployeeIds: [7],
    documents: 0,
    startDate: '2024-07-20',
  },
    {
    id: 'gst-002',
    title: 'Quarterly GST Filing',
    clientName: 'Retail Goods Co.',
    organization: 'Retail Goods',
    email: 'accounts@retailgoods.com',
    phone: '+91 78901 23456',
    category: 'GST',
    status: 'On Hold',
    priority: 'Medium',
    description: 'Filing of GSTR-1 and GSTR-3B for Q2.',
    progress: 25,
    assignedTeam: 'Finance Team',
    assignedEmployeeIds: [3, 8],
    documents: 4,
    startDate: '2024-07-01',
  }
];
